### PR TITLE
Depend on markupsafe

### PR DESCRIPTION
**Pull request by mweinelt**
Fixes compat with Flask 3.0, where importing markupsafe through it was removed.

https://github.com/pallets/flask/pull/4996

### CODE REVIEW

**Review by Tethik — APPROVED** [review]
LGTM! I'll try to give this project a bit more love and get PYPI publishing back up and running again for these changes to go through.

**Comment by mweinelt** [comment]
Note that `flask-sessionstore` which is used on the tests, has been archived in 2020, and is also not compatible with Flask 3.0.

**Comment by Tethik** [comment]
I haven't used Flask for a long time myself, hence this repo has been pretty stale. Is there a modern alternative to flask-sessionstore? Last I remember there were like 2-3 different forks :/

**Comment by mweinelt** [comment]
Not a user myself either, just refreshing our distro packages.

Flask-sessionstore seems to be a fork of [flask-session](https://github.com/pallets-eco/flask-session).

**Pull request merged**
